# 비동기 처리

- JS에서의 비동기 처리는 프로미스와 콜백 패턴 두가지가 있었다. 콜백 패턴의 경우 콜백이 여러 개 쌓이는 경우 가독성이 떨어지기 때문에, 요즘은 프로미스를 사용하는 편이다.

## 프로미스

- Promise는 비동기 상태를 값으로 다룰수 있는 객체로, 이를 사용하면 비동기 프로그래밍 시 동기 프로그래밍 방식으로 코딩할 수 있다.

```js
// using callback pattern
function requestData(callback) {
  setTimeout(() => {
    callback({ name: "avc", age: 23 });
  }, 1000);
}

function onSuccess(data) {
  console.log(data);
}
console.log("call requestData");
requestData(onSuccess);

// using promise
requestData1()
  .then((data) => {
    console.log(data);
    return requestData2();
  })
  .then((data) => {
    console.log(data);
    /// ...
  });
```

- promise를 생성하는 방식

```js
const p1 = new Promise((resolve, reject) => {}); // pending 상태의 프로미스 생성
const p2 = Promise.reject("error message"); // reject 상태의 프로미스 생성
const p3 = Promise.resolve(param); // fulfilled 상태의 프로미스 생성
```

- `new Promise((resolve, reject) => {});`

  - `{}` 내에서 비동기 처리가 끝나면, resolve 혹은 reject 둘 중 하나의 함수를 실행하게 된다.

- Promise의 상태

  - pending : 비동기 처리가 끝나지 않은 상태
  - fulfilled : 비동기 처리 이후 성공
  - rejected : 비동기 처리 이후 실패
  - settled = fulfilled + rejected

- 객체 Promise의 메서드 `then`
  - 비동기 처리 이후 할 일을 then 메서드로 정의할 수 있다.

```js
requestData().then(onResolve, onReject); // fulfilled시 onResolve 실행, rejected 시 onReject 실행
Promise.resolve(123).then((data) => console.log(data));
Promise.reject("error").then(null, (data) => console.log(data));
```

```js
Promise.reject("err") // reject 상태로 넘기므로, 다음 then은 reject 함수를 실행한다.
  .then(() => console.log("then 1")) // 하지만, reject 함수를 따로 정의하여 넘기지 않았으므로, 본 코드는 생략.
  .then(() => console.log("then 2")) // 하지만, reject 함수를 따로 정의하여 넘기지 않았으므로, 본 코드는 생략.
  .then(
    () => console.log("then 3"),
    () => console.log("then 4")
  ) // reject 함수가 실행되었고, 이 함수는 undefined를 반환하므로 fulfilled 상태가 된다.
  .then(
    () => console.log("then 5"),
    () => console.log("then 6")
  );

// then 4
// then 5
```

- 객체 Promise의 메서드 `catch`

  - then의 두번째 파라미터로 reject 함수를 넘기지만, catch 형태로 넘기는 것이 가독성에 좋다.
  - Promise의 에러처리를 위함.

```js
Promise.resolve()
  .then(() => {
    throw new Error("some error");
  })
  .catch((error) => {
    console.log(error);
  });
```

- 객체 Promise의 메서드 `finally`

  - reject, fulfilled 상태 모두 처리 가능.
  - finally 가 받은 Promise 객체를 다음 then/catch/finally로 그대로 넘겨준다. finally 내에서 반환하는 값과 상관 없다.

- Promise를 활용하여 서버 통신 후 값을 가져오는 경우

```js
function requestData() {
  return fetch()
    .catch((error) => {
      // ...
    })
    .finally(() => {
      sendLogToserver("requestData finished");
    });
}
requestData().then((data) => console.log(data));
```

- Promise를 병렬로 처리하는 방법 : 메서드 `all`
  - `all` 파라미터의 모든 함수가 fullfilled 상태여야 fulfilled 상태의 promise를 반환한다.

```js
Promise.all([requestData1(), reuqestData2()]).then(([data1, data2]) => {
  console.log(data1, data2);
});
```

## async-await

- 비동기 프로그래밍을 동기 프로그래밍 방식으로 작성하는 데 특화된 문법
- 하지만 Promise를 완벽히 대체하지는 못함. Promise는 객체로 존재하지만, async-await는 함수에 적용된다.

```js
async function getData() {
  return Promise.resolve(123); // return Promise.reject(123);
}
getData()
  .then((data) => console.log("fulfilled", data))
  .catch((data) => console.log("rejected", data));
```

- async 함수 내에서, await 키워드 오른쪽에 promise 객체를 입력하면 그 Promise가 settled 상태가 될 때까지 기다린다.

```js
function requestData(value) {
  return new Promise((resolve) =>
    setTimeout(() => {
      console.log("requestData:", value);
      resolve(value);
    }, 1000)
  );
}

async function printData() {
  const data1 = await requestData(10);
  const data2 = await requestData(20);
  console.log(data1, data2);
}

printData();
```

- await 키워드 오른쪽의 promise 객체가 reject 상태라면, 그 즉시 Promise 상태와 값을 return 한다.
- async-await 에서의 병렬 처리

```js
function asyncFunc1() {
  return new Promise((resolve) => {
    console.log("처리중1");
    setTimeout(() => {
      resolve(10);
    }, 1000);
  });
}
function asyncFunc2() {
  return new Promise((resolve) => {
    console.log("처리중2");
    setTimeout(() => {
      resolve(10);
    }, 1000);
  });
}

async function getData() {
  const p1 = asyncFunc1(); // p1 생성 즉시 함수 실행
  const p2 = asyncFunc2(); // p2 생성 즉시 함수 실행
  const data1 = await p1; // p1을 기다림
  const data2 = await p2; // p2를 기다림
  console.log({ data1, data2 });
}
getData();

async function getDataSimple() {
  const [data1, data2] = await Promise.all([asyncFunc1(), astncFunc2()]);
  console.log({ data1, data2 });
}
getDataSimple();
```

- async-await에서의 예외 처리 : try-catch 문

```js
async function getData() {
  try {
    await doAsync();
    return doSync();
  } catch (error) {
    console.log(error);
    return Promise.reject(error);
  }
}
```
